# Generated by Django 4.2.14 on 2024-07-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_published',
            field=models.BooleanField(blank=True),
        ),
    ]
