# Generated by Django 4.2.14 on 2024-08-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_document_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
